{% set name = "epimodels" %}
{% set version = "0.3.16" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 51f04576274fd3202a4bb1f4b1fd5e9eb26ba3bf3b68dca929888f801a454fb0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: The package home page
  license: mit
  license_family: MIT
  license_file: 
  summary: "Library of mathematical epidemic models for use in simulation studies and inference"
  doc_url: ""
  dev_url: "https://github.com/fccoelho/epimodels"

extra:
  recipe-maintainers:
    - fccoelho
